### ISSUE TITLE
can't change the default theme

### ISSUE THREAD

**Issue by nikhildaga** [Semantic-Org/Semantic-UI-Meteor#10]
When I change custom.semantic.json to

default: false,
material: true

I get the following error

While building the application:
   client/lib/semantic-ui/theme.import.less:15:1: Less compiler error: 'themes//default/globals/site.variables' wasn't found. Tried -
   client/lib/semantic-ui/themes/default/globals/site.variables,/home/shriram/Desktop/cookifi/client/lib/semantic-ui/definitions/collections/themes/default/globals/site.variables,themes/default/globals/site.variables
   client/lib/semantic-ui/theme.import.less:15:1: Less compiler error: 'themes//default/globals/site.variables' wasn't found. Tried -
   client/lib/semantic-ui/themes/default/globals/site.variables,/home/shriram/Desktop/cookifi/client/lib/semantic-ui/definitions/elements/themes/default/globals/site.variables,themes/default/globals/site.variables
   client/lib/semantic-ui/theme.import.less:15:1: Less compiler error: 'themes//default/globals/site.variables' wasn't found. Tried -
   client/lib/semantic-ui/themes/default/globals/site.variables,/home/shriram/Desktop/cookifi/client/lib/semantic-ui/definitions/globals/themes/default/globals/site.variables,themes/default/globals/site.variables
   client/lib/semantic-ui/theme.import.less:15:1: Less compiler error: 'themes//default/globals/site.variables' wasn't found. Tried -
   client/lib/semantic-ui/themes/default/globals/site.variables,/home/shriram/Desktop/cookifi/client/lib/semantic-ui/definitions/modules/themes/default/globals/site.variables,themes/default/globals/site.variables
   client/lib/semantic-ui/theme.import.less:15:1: Less compiler error: 'themes//default/globals/site.variables' wasn't found. Tried -
   client/lib/semantic-ui/themes/default/globals/site.variables,/home/shriram/Desktop/cookifi/client/lib/semantic-ui/definitions/views/themes/default/globals/site.variables,themes/default/globals/site.variables
   client/lib/semantic-ui/theme.import.less:15:1: Less compiler error: 'themes//default/globals/site.variables' wasn't found. Tried -
   client/lib/semantic-ui/themes/default/globals/site.variables,/home/shriram/Desktop/cookifi/client/lib/semantic-ui/themes/default/globals/site.variables,themes/default/globals/site.variables

=> Your application has errors. Waiting for file change.

**Comment by flemay** [comment]
The first line of the error is quite descriptive:

> client/lib/semantic-ui/theme.import.less:15:1

I would probably look at this file.

**Comment by nikhildaga** [comment]
That file is auto-generated . 
/*
  DO NOT MODIFY - This file has been generated and will be regenerated
  Semantic UI v1.12.1
*/

Line 15: 
@import "@{themesFolder}/default/globals/site.variables";

**Comment by nooitaf** [comment]
now i would look at the @themesFolder variable

**Comment by nikhildaga** [comment]
@nooitaf :  In theme.config.import.less, line 79,  
@themesFolder : 'themes/';  

Can you change the default theme to something else say material or amazon without any problem?

**Comment by flemay** [comment]
My bad. it is the file `theme.config.import.less` that needs to be changed. 

Since you can specify a specific theme to a specific element I don't think you can change the default theme to something else without any "problem".

**Comment by nikhildaga** [comment]
@flemay : Thank you for your response. But that's the problem. Wherever I change the default theme to something else, I start getting errors.

Can you please once check if you too get errors while changing the default theme ? Maybe then you can fix.

**Comment by flemay** [comment]
Would you mind to be more specific? What is inside `theme.config.import.less` and `custom.semantic.json`? :)

**Comment by garrilla** [comment]
I have the same problem @flemay 

`custom.sematic.json`

``` javascript
{
  "definitions": {
    "accordion": true,
    "ad": true,
    "api": true,
    "breadcrumb": true,
    "button": true,
    "card": true,
    "checkbox": true,
    "colorize": true,
    "comment": true,
    "dimmer": true,
    "divider": true,
    "dropdown": true,
    "feed": true,
    "flag": true,
    "form": true,
    "grid": true,
    "header": true,
    "icon": true,
    "image": true,
    "input": true,
    "item": true,
    "label": true,
    "list": true,
    "loader": true,
    "menu": true,
    "message": true,
    "modal": true,
    "nag": true,
    "popup": true,
    "progress": true,
    "rail": true,
    "rating": true,
    "reset": true,
    "reveal": true,
    "search": true,
    "segment": true,
    "shape": true,
    "sidebar": true,
    "site": true,
    "state": true,
    "statistic": true,
    "step": true,
    "sticky": true,
    "tab": true,
    "table": true,
    "transition": true,
    "video": true,
    "visibility": true,
    "visit": true
  },
  "themes": {
    "amazon": false,
    "basic": false,
    "bookish": false,
    "bootstrap3": false,
    "chubby": false,
    "classic": false,
    "default": false,
    "duo": false,
    "fixed": false,
    "flat": false,
    "github": false,
    "gmail": false,
    "material": true,
    "pulsar": false,
    "raised": false,
    "resetcss": false,
    "round": false,
    "rtl": false,
    "striped": false,
    "timeline": false,
    "twitter": false
  }
}
```

`theme.config.import.less`

``` javascript
/*

████████╗██╗  ██╗███████╗███╗   ███╗███████╗███████╗
╚══██╔══╝██║  ██║██╔════╝████╗ ████║██╔════╝██╔════╝
   ██║   ███████║█████╗  ██╔████╔██║█████╗  ███████╗
   ██║   ██╔══██║██╔══╝  ██║╚██╔╝██║██╔══╝  ╚════██║
   ██║   ██║  ██║███████╗██║ ╚═╝ ██║███████╗███████║
   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝╚══════╝

*/

/*******************************
        Theme Selection
*******************************/

/* To override a theme for an individual element
   specify theme name below
*/

/* Global */
@site       : 'default';
@reset      : 'default';

/* Elements */
@button     : 'default';
@divider    : 'default';
@flag       : 'default';
@header     : 'default';
@icon       : 'default';
@image      : 'default';
@input      : 'default';
@label      : 'default';
@list       : 'default';
@loader     : 'default';
@rail       : 'default';
@reveal     : 'default';
@segment    : 'default';
@step       : 'default';

/* Collections */
@breadcrumb : 'default';
@form       : 'default';
@grid       : 'default';
@menu       : 'default';
@message    : 'default';
@table      : 'default';

/* Modules */
@accordion  : 'default';
@checkbox   : 'default';
@dimmer     : 'default';
@dropdown   : 'default';
@modal      : 'default';
@nag        : 'default';
@popup      : 'default';
@progress   : 'default';
@rating     : 'default';
@search     : 'default';
@shape      : 'default';
@sidebar    : 'default';
@sticky     : 'default';
@tab        : 'default';
@transition : 'default';
@video      : 'default';

/* Views */
@ad         : 'default';
@card       : 'default';
@comment    : 'default';
@feed       : 'default';
@item       : 'default';
@statistic  : 'default';

/*******************************
            Folders
*******************************/

/* Path to theme packages */
@themesFolder : 'themes/';

/* Path to site override folder */
@siteFolder  : 'site/';

/*******************************
         Import Theme
*******************************/

@import "theme.import.less";

/* End Config */
```

**Comment by garrilla** [comment]
I note that `./client/lib/semantic-ui/themes/` only has the `default` directory

it doesn't contain any of the pre-packaged themes

**Comment by flemay** [comment]
`theme.config.import.less` is where you set theme to each of the element. From this file, all elements are set to theme `default`. 

from `custom.sematic.json` I can see you set `default: false` and `material: true`. See the problem? If you want to you use some themes you need to set those to `true` and apply the theme you want to each element.

The package should generate for you the themes that are set to true.

**Comment by garrilla** [comment]
If I understand you I should set `custom.sematic.json` to have `default: false` and `material: true` and then in `theme.config.import.less` I should set each variable to `material` e.g.

``` javascript

/* Global */
@site       : 'material';
@reset      : 'material';

/* Elements */
@button     : 'material';
@divider    : 'material';
@flag       : 'material';
@header     : 'material';
@icon       : 'material';
@image      : 'material';
@input      : 'material';
@label      : 'material';
@list       : 'material';
...
```

this still yields an error

```
   While building the application:
   client/lib/semantic-ui/theme.import.less:23:1: Less compiler error: 'themes//material/globals/reset.variables' wasn't found. Tried -
   client/lib/semantic-ui/themes/material/globals/reset.variables,/home/garrilla/projects/blog/client/lib/semantic-ui/themes/material/globals/reset.variables,themes/material/globals/reset.variables

```

now `client/lib/semantic-ui/themes/material/globals/` exists with only `site.overides` and `site.variables`

**Comment by flemay** [comment]
You should look into `meterial` folder to see which elements it customises. Most likely it will be just a few and the rest should be set to `default`. (In this case you would also need to set `default: true`.)

**Comment by garrilla** [comment]
OK, that works. Thanks @flemay 

Obvious now, but wasn't clear from the readme. If I get a chance today, I'll post a PR to the readme.

**Comment by jlukic** [comment]
I'm a bit confused. Themes are _per ui element_ but the custom json file you are using for the project has one global themes setting.

I haven't written any themes that are available on every UI component. So it seems to me that would always fail?

**Comment by garrilla** [comment]
Yes, that's right @jlukic 

It wasn't clear to me that was _per ui element_ and that each theme only had a limited set of elements.

In part in wasn't clear in the Readme but the `@global` and `@site` variables added further confusion.

**Comment by flemay** [comment]
@jlukic the global setting is there for the user to choose which themes he wants to be generated. Otherwise all themes would be there. And then he has to choose which theme to apply _per ui element_ in the file `theme.config.import.less`.

Beside the fact the `README` might not be clear on that, isn't the Semantic UI approach? :)

**Comment by garrilla** [comment]
I can see 3 points where this confused me...
1. While I can see in the future that `default: false` might be possible, that seems unlikely. And at present it is always required that `default: true` 
2. Similarly, at present `@global` and `@site` are redundant. 
3. Every element is available, when on per theme basis only a small number are actually (`button`, `segment`, `header`, `loader`, `message`, `step`)   

Saying that, when it is understood, it makes sense. However, I believe logic should be inductive.

**Comment by afang** [comment]
It would be good to leave a comment on `default: true` as this is a frequent issue.

**Comment by awt2542** [comment]
Just ran into this issue. glad I found the solution :) two things were not really clear to me: 1. themes doesn't necessarily cover all elements. 2. default needs to be enabled because of this. some extra comments inside theme.config.import.less would be nice!
