### ISSUE TITLE
Can't find files when running in subdirectory

### ISSUE THREAD

**Issue by justindra** [Semantic-Org/Semantic-UI-Meteor#103]
If running the meteor app in a subdirectory of a domain (`https://domain.name.com/subdir/`), receives this error.

```
Failed to load resource: the server responded with a status of 404 (Not Found)
https://domain.name.com/lib/semantic-ui/src/themes/default/assets/fonts/icons.ttf
```

The url should be changed to include the subdirectory

```
https://domain.name.com/subdir/lib/semantic-ui/src/themes/default/assets/fonts/icons.ttf
```

**Comment by fvpDev** [comment]
What does your folder structure look like?
If you are running meteor app from a subdirectory (huh?) then meteor only recognizes code within the directory in which it is running. I am personally not sure how exactly meteor recognizes the domain at which it's located (maybe via environmental variables?) but this seems to not be a semantic-ui issue, so I will close. Feel free to re-open if problem persists/you have more info.
