### ISSUE TITLE
Suddenly none of the overrides work

### ISSUE THREAD

**Issue by filipblaauw** [Semantic-Org/Semantic-UI-Meteor#108]
I had a few overrides in `site.overrides.import.less` but they suddenly stopped working. I'm just seeing the default template again without my changes.

Is there a way to force Semantic to rebuild? I'v tried stopping and starting Meteor, but there's no response.

**Comment by fvpDev** [comment]
Did you try deleting the `.custom.semantic.json` file?
http://semantic-ui.com/introduction/integrations.html#start-meteor--generate

**Comment by next-franciscocalle** [comment]
Same happens to me. Removing the file does not solve it.

**Comment by luisivan** [comment]
Same situation. Removing the file doesn't work.

**Comment by luisivan** [comment]
@beeva-franciscocalle @filipblaauw including Semantic from other file inside the project (`@import '/client/lib/semantic-ui/semantic.less';`) seems to force a reload. Weird but works.

**Comment by talha-asad** [comment]
Why does this happen, though.

This is a bug. Keep this issue open till a fix is made.

**Comment by eadsjr** [comment]
I had to deal with this problem.

@luisivan 's import suggestion fixed it for now.

This should be fixed.
