### ISSUE TITLE
Less files are processed by Meteor multiple times

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-Meteor#11]
All less files that are imported by another less file should end with `.import.less`, so they don't get processed individually.

EDIT: The less files in the definitions folder don't have the .import.less extension. All other files have it.

**Comment by flemay** [comment]
Yes you are absolutely right! Don't know why I left them out :S

**Comment by flemay** [comment]
Package version 1.12.1_1 includes now `.import.less` :)
