### ISSUE TITLE
variable override bug in menu

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI-Meteor#110]
I'm using the Meteor package (2.2.1) for SUI.

in my theme's `/collection/menu.variables.import.less` flie I added `@largeWidth = 16rem;` which should change the width of my vertical menu, but something is wrong with the build process because it's not overriding. We tested things over and over and we're pretty sure this is a bug.

`theme.config.import.less` is setup to use my theme

```
...
/* Collections */
@breadcrumb: 'default';
@form: 'default';
@grid: 'default';
@menu: 'blackship';
@message: 'default';
@table: 'default';
...
```

But the style in my app comes out as 18rem (the default) not 16rem (my override)
```
.ui.large.inverted.vertical.menu {
    width: 18rem;
}
```

**Comment by nooitaf** [comment]
should it not be..
```less
@largeWidth: 16rem;
```
instead of
```less
@largeWidth = 16rem;
```
feel free to reopen
