### ISSUE TITLE
Can not get a modal to work

### ISSUE THREAD

**Issue by partounian** [Semantic-Org/Semantic-UI-Meteor#113]
$(...).modal is not a function is the error I get in the console. I have been trying to figure this out with a friends for hours.

We re

HTML:
```
<template name="testForm">  
	<div class="ui modal">  
	  <i class="close icon"></i>  
	     <div class="header">Test</div>  
	</div>
</template>
```

JS:
```
Template.testForm.onRendered(function () {  
   this.$('.ui.modal').modal();  
   this.$('.ui.modal').modal('show');  
});  
```

EDIT: When looking in dev tools it all seems to be loaded in the correct order. I have tried using this., tried putting it in a <script> in the html itself and also tried using the JS you see above.

**Comment by partounian** [comment]
things work now and I don't know why exactly

EDIT: 
Nothing was actually included for s-ui. Things were fixed by moving the folder from lib/imports/ui/client into client/lib/.

**Comment by nooitaf** [comment]
related https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/60
