### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ziarno** [Semantic-Org/Semantic-UI-Meteor#116]
I'm getting a strange error after trying to run an app I developed a year ago:

```

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While processing files with less (for target web.browser):
   client/lib/semantic-ui/semantic.less: Maximum call stack size exceeded
   
=> Your application has errors. Waiting for file change.
                                              
```

The semantic.less file is of course generated automatically by semantic ui. Any idea what's causing this issue?
I

**Comment by nooitaf** [comment]
Did you upgrade Meteor to 1.3+? 
Did you remove ` flemay:less-autoprefixer` and `standard-minifier-css` 
https://github.com/Semantic-Org/Semantic-UI-Meteor#meteor-13-1

**Comment by ziarno** [comment]
Yep, both gone. I only have `juliancwirko:postcss`

**Comment by ziarno** [comment]
I've upgraded to meteor 1.4, but it worked on 1.3 before

**Comment by nooitaf** [comment]
i hope you also added `less` and `jquery` 
```
meteor add less jquery
```
and added the following to package.json
```
{
  "devDependencies": {
    "autoprefixer": "^6.3.1"
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {"browsers": ["last 2 versions"]}
    }
  }
}
```
and you ran this once
```
meteor npm install
```

**Comment by ziarno** [comment]
Yep, I've got it all - I don't know what happened, but after I removed the directory and recloned it from repo this issue doesn't occur anymore... thanks for help, and sorry for the trouble!

**Comment by nooitaf** [comment]
No trouble, glad it worked out :)
