### ISSUE TITLE
Sample Starter HTML

### ISSUE THREAD

**Issue by jared201** [Semantic-Org/Semantic-UI-Meteor#128]
Hi,

I want to refactor this HTML to be meteor-compatible is there any samples I can follow?

https://semantic-ui.com/examples/homepage.html

thanks!

**Comment by nooitaf** [comment]
Don't know a sample, but essentially you could 
- remove all css and script links (those are in the semantic package, so is jQuery)
- add the custom css into your apps css file (they are overrides of the linked defaults)
- add the custom javascript (sidebar+masthead) from inside the `.ready()` into your `.onRendered()` function
- make templates of the parts you need (optional)

**Comment by jared201** [comment]
thanks , i managed to do complete it today!
