### ISSUE TITLE
jQuery not defined

### ISSUE THREAD

**Issue by yiluxin** [Semantic-Org/Semantic-UI-Meteor#14]
```
W20150516-14:51:28.683(8)? (STDERR)  
W20150516-14:51:28.689(8)? (STDERR) /Users/yiluxin/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150516-14:51:28.690(8)? (STDERR)                                             throw(ex);
W20150516-14:51:43.307(8)? (STDERR)                                                   ^
W20150516-14:51:43.312(8)? (STDERR) ReferenceError: jQuery is not defined
W20150516-14:51:43.312(8)? (STDERR)     at app/ui/definitions/behaviors/api.js:875:5
W20150516-14:51:43.312(8)? (STDERR)     at app/ui/definitions/behaviors/api.js:877:3
W20150516-14:51:43.312(8)? (STDERR)     at /Users/yiluxin/WebstormProjects/untitled/.meteor/local/build/programs/server/boot.js:222:10
W20150516-14:51:43.312(8)? (STDERR)     at Array.forEach (native)
W20150516-14:51:43.312(8)? (STDERR)     at Function._.each._.forEach (/Users/yiluxin/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150516-14:51:43.313(8)? (STDERR)     at /Users/yiluxin/WebstormProjects/untitled/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8  
=> Your application is crashing. Waiting for file change.
```

**Comment by flemay** [comment]
Maybe a bit of context? Existing app or brand new? :)

**Comment by yiluxin** [comment]
I tried again, deployed in the lib folder of meteor client folder, everything is normal, as the problem of path, but still don't understand why

**Comment by joryphillips** [comment]
It's been a few weeks but I think this is what was happening to me when I was attempting to convert an app from Bootstrap. I tried to go through and rebuild it piece-by-piece to find out what the cause was, but it was too much work. :)

**Comment by kctang** [comment]
Same issue. I managed to generate semantic-ui after editing custom.semantic.json. After that, it got stuck with the error message above ... ReferenceError: jQuery is not defined.

I am doing a new/simple demo app. I will tried to `meteor add jquery` for the project. Problem did not go away. I will try to manually paste jQuery in lib/definitions/behavior later and see what happens.

I notice the generated `lib/definitions/behaviors/api.js` needs jquery:

```javascript
(function ( $, window, document, undefined ) {
  ...
})( jQuery, window , document );
```

Any pointer would be appreciated.

**Comment by kctang** [comment]
Yay! I managed to get Semantic UI to work by creating `custom.semantic.json` in `client/lib`.

Previously, I placed it in `/lib` directory causing Meteor to process it as server side code. It would be good to put this in README.md's "Usage" section so that new Meteor users like myself do not make such mistake.

**Comment by joryphillips** [comment]
Additional note: I went back and attempted to recreate this error, and was unable to.

**Comment by splendido** [comment]
Anyone willing to try adding the following section to the `package.js` file?

``` javascript
Package.onUse(function(api) {
  api.versionsFrom('1.0.1');
  api.imply('jquery', 'client');
});
```

At the moment we're not requiring jquery explicitely, so I guess there are no problems if in the same project the are other packages implying it, but could be required to solve your issues.

Unfortunately I have no time to test this :(

**Comment by flemay** [comment]
@kctang Thanks a lot for testing the package and finding the problem. :)

@splendido Good suggestion but unfortunately it didn't solve the problem. I think the best approach would be what @kctang suggested.

Also thanks to @yiluxin and @joryphillips!

**Comment by splendido** [comment]
...woops, I've missed the comment by @kctang :(
Any way to intercept this case and print a warning on the server?

**Comment by flemay** [comment]
The problem is not the package itself because it only generates files. It does not compile anything. :) Maybe `flemay:less-autoprefixer` could..

**Comment by xtfer** [comment]
@kctang's solution is the correct one. jQuery is not available on the server, only the client. I would suggest updating the documentation accordingly.

**Comment by splendido** [comment]
See [this comment](https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/43#issuecomment-127223550) from @leijing7 which seems to clarify why you can get `jQuery is not defined`...

**Comment by dbj** [comment]
It is only necessary to put `custom.semantic.json` under the `/client` folder, not necessarily in `/client/lib`.  For example, I put `custom.semantic.json` in `/client/semantic-ui`.

**Comment by sheshmantha** [comment]
in my simple-todo tutorial on Windows, there's no /client folder... Added client\semantic-ui and moved the custom.semantic.json to that folder... still experiencing the same issue.

It looks like it's generating some files... see image: `definitions`, `site`, `themes`... but the build on windows seems to only have `server` and `web.browser` files... wonder if  `\client` should be `\web.browser`... will try.

![image](https://cloud.githubusercontent.com/assets/3171978/10143845/86093f4c-65e8-11e5-9ef1-1a40891b71e8.png)

--- Tried `web.browser` same result ---

thoughts??

**Comment by sheshmantha** [comment]
@sheshmantha -- OK here was the issue:
1. First I added the file in root folder -- so when I had custom.semantic.json in the root folder for the project, the 3 folders of definitions, sites, themes along with the .less files were created in that folder.
2. afterwards I created a subfolder of client\semantic-ui and moved _ONLY_ the custom.semantic.json to that folder... 

That kept crashing (even though new definitions, less files were in the client\semantic-ui)... after a bit of aggravation, I noticed these folders and files in the root project folder... _AND_ when i removed them and restarted... _VOILA_ she works!!

**Comment by TimeBandit** [comment]
@sheshmantha this worked for me too and had the added benefit of clearing up the files from the root folder

**Comment by rajakedia1** [comment]
I m not getting, How to solve this problem. I am using windows and I am having this problem in starting meteor. Plz suggest me how to solve it..

**Comment by nooitaf** [comment]
@rajakedia1 To solve this problem, make sure you create your `custom.semantic.json` in a `/client/..` folder, so meteor treats it as _frontend code only_ and not as server code which has no jQuery.
