### ISSUE TITLE
Cannot find module 'postcss-load-config'

### ISSUE THREAD

**Issue by ni-vo** [Semantic-Org/Semantic-UI-Meteor#140]
Trying a fresh install and am getting the following errors:

=> Errors prevented startup:                  
   
   While loading plugin `minifier-postcss` from package `juliancwirko:postcss`:
   packages/modules-runtime.js:231:12: Cannot find module 'postcss-load-config'
   at makeMissingError (packages/modules-runtime.js:231:12)
   at require (packages/modules-runtime.js:241:19)
   at minify-css.js (packages/minifier-postcss/plugin/minify-css.js:17:12)
   at fileEvaluate (packages/modules-runtime.js:343:9)
   at require (packages/modules-runtime.js:238:16)
   at <runJavaScript-30>:279:1
   at <runJavaScript-30>:284:3

Not sure what I missed, any suggestions?

**Comment by vnmone** [comment]
There is some problems with postcss.
Add next lines into your devDependencies in package.json

```JSON
"postcss": "^6.0.22",
"postcss-load-config": "^1.2.0"
```

my devDependencies:
```JSON
  "devDependencies": {
    "autoprefixer": "^6.3.1",
    "postcss": "^6.0.22",
    "postcss-load-config": "^1.2.0"
  }
```

and run `meteor npm install`

**Comment by JulianKeller** [comment]
That fixed this exact issue for me. Thanks!

**Comment by Da0sy** [comment]
When I run "meteor cnpm install", I report an error:
The meteor item cannot be identified as the name of a cmdlet, function, script file, or runnable program.
What should I do?

**Comment by nooitaf** [comment]
@Da0sy I don't know how this unrelated question got here, but it's ```meteor npm install``` not ```meteor cnpm install```

**Comment by Da0sy** [comment]
Ok,thank you very much!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ralf Brandenstein"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月29日(星期天) 晚上10:50
收件人： &nbsp;“语义组织/语义UI流星” <Semantic-UI-Meteor@noreply.github.com&gt;;
抄送： &nbsp;“ ？???？ ” <993397125@qq.com&gt;;“提及” <mention@noreply.github.com&gt;;
主题： &nbsp;回复：[Semantic-Org / Semantic-UI-Meteor]找不到模块'postcss-load-config'（＃140）





 
@ Da0sy我不知道这个无关的问题是怎么来的，但是meteor npm install不是meteor cnpm install
  
- 
您收到此邮件是因为有人提到您。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by niklasdahlheimer** [comment]
It looks like this is still an issue in 2020. If it's still an will be nessecary to add those lines
```
"postcss": "^6.0.22",
"postcss-load-config": "^1.2.0"
```
in the `devDependencies`, shouldn't that be mentioned in the Meteor section of the [Integrations guide](https://semantic-ui.com/introduction/integrations.html) ? Without the information from this closed issue, the integration guide leads to an faulty and not startable meteor app. Or am I wrong about this?

**Comment by nooitaf** [comment]
@niklasdahlheimer i think you are correct, thank you. I added it to the Readme.

**Comment by nooitaf** [comment]
Hmm.. i might add that i tried to get semantic working in meteor 2.0 and realized it doesn't need any deps, devdeps or post-css except the default `meteor add semantic:ui less`. I had to manually change some less files tho. One import to multiple and some stringified calcs to non-stringified. It compiles and runs (at least in my project) but didn't run no tests to see if everything is working as expected.

Just for reference.. the files i changed:

One import to multiple... (fixing: global variables missing error)
File: `theme.config.import.less` 
```less
@import "theme.import.less";
// into
@import (multiple) "theme.import.less";
```

File: `theme.import.less` .. (fixing global variable missing in google url)
```less
@import url('@{googleProtocol}fonts.googleapis.com/css?family=@{googleFontRequest}');
// into 
@gimport url('@{googleProtocol}fonts.googleapis.com/css?family=@{googleFontRequest}');
```

In the following files i changed the calc functions.. (fixing: Operation on an invalid type error)
`/themes/default/collections/table.variables.import.less`
`/themes/default/collections/menu.variables.import.less`
`/themes/default/elements/label.variables.import.less`
`/themes/default/elements/segment.variables.import.less`
`/themes/default/elements/step.variables.import.less`

Example
```less
@attachedWidth: ~"calc(100% + "-@attachedHorizontalOffset * 2~")";
// into 
@attachedWidth: calc(100% + -@attachedHorizontalOffset * 2);
```

I have the `basic` and `default` theme enabled.

Maybe this helps someone. I have almost zero experience with less, so this might be totally wrong what i did here.

**Comment by jpdewing** [comment]
> Hmm.. i might add that i tried to get semantic working in meteor 2.0 and realized it doesn't need any deps, devdeps or post-css except the default `meteor add semantic:ui less`. I had to manually change some less files tho. One import to multiple and some stringified calcs to non-stringified. It compiles and runs (at least in my project) but didn't run no tests to see if everything is working as expected.
> 
> Just for reference.. the files i changed:
> 
> One import to multiple... (fixing: global variables missing error)
> File: `theme.config.import.less`
> 
> ```css-less
> @import "theme.import.less";
> // into
> @import (multiple) "theme.import.less";
> ```
> 
> File: `theme.import.less` .. (fixing global variable missing in google url)
> 
> ```css-less
> @import url('@{googleProtocol}fonts.googleapis.com/css?family=@{googleFontRequest}');
> // into 
> @gimport url('@{googleProtocol}fonts.googleapis.com/css?family=@{googleFontRequest}');
> ```
> 
> In the following files i changed the calc functions.. (fixing: Operation on an invalid type error)
> `/themes/default/collections/table.variables.import.less`
> `/themes/default/collections/menu.variables.import.less`
> `/themes/default/elements/label.variables.import.less`
> `/themes/default/elements/segment.variables.import.less`
> `/themes/default/elements/step.variables.import.less`
> 
> Example
> 
> ```css-less
> @attachedWidth: ~"calc(100% + "-@attachedHorizontalOffset * 2~")";
> // into 
> @attachedWidth: ~calc(100% + -@attachedHorizontalOffset * 2~);
> ```
> 
> I have the `basic` and `default` theme enabled.
> 
> Maybe this helps someone. I have almost zero experience with less, so this might be totally wrong what i did here.

Thanks for posting this information - really helpful :)
