### ISSUE TITLE
Missing globals folder?

### ISSUE THREAD

**Issue by jbulchergist** [Semantic-Org/Semantic-UI-Meteor#15]
meteor crashes after setting up custom.semantic.json:

```
Your app is crashing. Here's the latest log.

=> Meteor server restarted
=> Client modified -- refreshing (x4)
Errors prevented startup:

While building the application:
client/css/semantic/theme.import.less:15:1: Less compiler error: 'themes//default/globals/site.variables' wasn't found

Your application has errors. Waiting for file change.
```

The themes folder only contains the `default` folder; there is no folder named `globals`.

To install, I created a folder called `semantic`, and placed a file called `custom.semantic.json` in it. I edited the definitions, but left only the default theme on.

**Comment by jbulchergist** [comment]
Enabling the `site` definition fixed the issue; the theme.import.less breaks when the `site` definition is not enabled.

**Comment by joetm** [comment]
Thanks. I had the same problem (missing site.variables file and globals folder) and that fixed it.

**Comment by 1devNdogs** [comment]
Thanks. Works too!

**Comment by mvenaas** [comment]
As far as I know this isn't mentioned in the README file. It seems to be a common problem so it might be worth putting it in there.

**Comment by 1devNdogs** [comment]
After checking, this is the custom.semantic.json that iam using and i put it in the client/lib folder, i think default must be always true, when I set default as false it remove all the files under themes/default/globals/ so it just cant find it, is default template like a dependency for others templates? this works for me, hope helps in some way.

{
  "definitions": {
    "accordion": true,
    "ad": true,
    "api": true,
    "breadcrumb": true,
    "button": true,
    "card": true,
    "checkbox": true,
    "colorize": true,
    "comment": true,
    "container": true,
    "dimmer": true,
    "divider": true,
    "dropdown": true,
    "embed": true,
    "feed": true,
    "flag": true,
    "form": true,
    "grid": true,
    "header": true,
    "icon": true,
    "image": true,
    "input": true,
    "item": true,
    "label": true,
    "list": true,
    "loader": true,
    "menu": true,
    "message": true,
    "modal": true,
    "nag": true,
    "popup": true,
    "progress": true,
    "rail": true,
    "rating": true,
    "reset": true,
    "reveal": true,
    "search": true,
    "segment": true,
    "shape": true,
    "sidebar": true,
    "site": true,
    "state": true,
    "statistic": true,
    "step": true,
    "sticky": true,
    "tab": true,
    "table": true,
    "transition": true,
    "visibility": true,
    "visit": true
  },
  "themes": {
    "amazon": false,
    "basic": false,
    "bookish": false,
    "bootstrap3": false,
    "chubby": false,
    "classic": true,
    "colored": false,
    "default": true,
    "duo": false,
    "fixed": false,
    "flat": false,
    "github": false,
    "gmail": false,
    "instagram": false,
    "material": false,
    "pulsar": false,
    "raised": false,
    "resetcss": false,
    "round": false,
    "rtl": false,
    "striped": false,
    "timeline": false,
    "twitter": false
  }
}

**Comment by tvld** [comment]
Experiencing this issue again in  2.1.4_5   But adding `"site": true` does not help
I have the json in`/lib/semantic-ui/client`

**Comment by nooitaf** [comment]
The `default` theme should always be true. All other themes just override it's values.
