### ISSUE TITLE
Meteor Integration of Semantic UI 2.0 version?

### ISSUE THREAD

**Issue by fvpDev** [Semantic-Org/Semantic-UI-Meteor#17]
I'm really interested in implementing the "ui container" element that is coming out with 2.0 in several days, and can do fine with "ui page grid" for now, but I was wondering if when/where that is on your priority list and whether I should wait or just go with page grids for now?

**Comment by flemay** [comment]
According to https://github.com/Semantic-Org/Semantic-UI/issues/2216#issuecomment-107630467, the release of 2.0 is very close!

Once it is out, semantic:ui will also be updated :)

**Comment by fvpDev** [comment]
Woot woot! Thanks!

**Comment by louwers** [comment]
Since the release got delayed, I'm curious: did you figure out how to use the beta version of 2.0 with Meteor?

**Comment by fvpDev** [comment]
Well there is always the way of using something like meteorhacks:npm and installing semantic-ui as a node package but I haven't tried it yet; I've just decided to wait until the release. Hopefully it won't be too much longer.

**Comment by louwers** [comment]
Indeed, looking forward to the official release!

Only the fonts are unavailable if you just copy the dist folder inside `client`, so you can opt to go with that also.

**Comment by fvpDev** [comment]
Kewl thank you for that!

**Comment by jlukic** [comment]
I'm going to be adding integration "getting started" guides (Meteor, Ember, etc) into documentation for 2.0. 

@flemay Is it alright just to use the content from the readme?

**Comment by louwers** [comment]
The man himself!

Also, **fvpDev**, put `themes` in public (assuming you are using iron-router) and everything should be fully functional without this package.

**Comment by flemay** [comment]
@jlukic It is fine as long as the "getting started" can be updated. The actual readme needs a bit of rework because many people get confused when it comes to themes.
