### ISSUE TITLE
Workflow needs improving

### ISSUE THREAD

**Issue by DEfusion** [Semantic-Org/Semantic-UI-Meteor#18]
From my initial experience changes made to `custom.semantic.json` always cause errors until you delete the `site` folder. I did the same when trying to change themes (deleted the `themes` folder but now get a different error.

I'm happy to look at a patch that improves this, if feasible.

**Comment by flemay** [comment]
Hi @DEfusion,

Would you mind to share step by step of what you did? I am interested to understand your flow.

Thanks,
Fred

**Comment by DEfusion** [comment]
Ok the issue I seem to be having is adding things back to semantic UI as I set a lot of definitions to false on my initial setup and am just adding things in as needed.

So if I have:

```
{
  "definitions": {
    "accordion": false,
    "ad": false,
    "api": false,
    "breadcrumb": false,
    "button": true,
    ...
}
```

Then change it so accordion is true I get the following error:

```
client/lib/semantic-ui/theme.import.less:30:1: Less compiler error: 'site//modules/accordion.variables.import.less' wasn't found. 
```

In order to resolve this error I then tried deleting the dotfile and re-saving custom.semantic.json but that keeps the error. So I have to delete the `site` folder, which then gives you a similar error:

```
client/lib/semantic-ui/theme.import.less:29:1: Less compiler error: 'site//globals/site.variables.import.less' wasn't found
```

So I delete the dotfile again make a change to `custom.semantic.json` again and now it works.

Obviously I've now learnt that before editing `custom.semantic.json` I should just delete the `site` folder first but as this directory is not user editable shouldn't the package be smarter about when definitions are changed to avoid this little bump in the experience.

**Comment by flemay** [comment]
Thank you for the write up.

I didn't want to touch `site` once it's being generated because it is customized by the user. In your case, instead of deleting `site` to re-generate it, you could just manually add the folder with the element's name and the files inside `site`. :)

Maybe the readme should be more explicit about it although it has the following

> site/
> This folder contains your current site's theme. It is generated only when it does not exist. Therefore if you change custom.semantic.json to turn definitions/themes on/off, then it will not affect site/. You will either need to add/remove files in site/ or remove the site/ folder so it can be regenerated again.

**Comment by DominikGuzei** [comment]
Hey there, I also think the workflow is pretty flawed – in most cases i don't want to customize a module and having all these empty extra files in the code repository is also not really exciting.

I would much rather prefer that those overrides are optional and can be ignored most of the time until you really need to customize something.

**Comment by jlukic** [comment]
@DominikGuzei The less imports in the soon-to-be `2.0` version are optional (since less added the ability for optional imports). You can safely delete them if you have no overrides.

**Comment by DominikGuzei** [comment]
Hey @jlukic! Awesome, let me know when it is available :+1:

**Comment by flemay** [comment]
@jlukic which version of less for optional imports?

**Comment by DominikGuzei** [comment]
Hey there! Can you give some directions how to enable the optional imports? i just updated to `flemay:less-autoprefixer@1.0.2` which loads less 2.5.1 but I still get the same errors. Do I have to override some config var to make the imports optional?

**Comment by jlukic** [comment]
@DominikGuzei You'll have to wait till 2.0 comes later today that uses `@import (optional)` in the source code.
