### ISSUE TITLE
Defining variables for /site/globals/site.variables"

### ISSUE THREAD

**Issue by artshostak** [Semantic-Org/Semantic-UI-Meteor#21]
Hello,

Where would one define the global variables for Semantic UI — specifically for the **@headerFont**, **@pageFont** and **@importGoogleFonts** options? Would like to follow this guide and specify some customizations: http://learnsemantic.com/developing/customizing.html#setting-global-variables

And is there a preferred method for regenerating the package afterwards?

Thanks!

**Comment by fvpDev** [comment]
Have you created a "custom.semantic.json" file yet as per instructions? 
https://atmospherejs.com/semantic/ui

If you have (and once you run "meteor" in command) the folder structure will be built and you can then edit those vars in "src/site/globals/site.variables"..."src" being the folder in which your custom.semantic.json file is located.
http://learnsemantic.com/developing/customizing.html#setting-global-variables

As for regeneration of the package, I'm not quite sure what you mean... I know that the less autoprefixer and meteor will automatically rebuild the output css for the browser as soon as a file change is detected.

**Comment by artshostak** [comment]
Thanks, I wasn't originally sure if that "src/site/globals/site.variables" file was alright to edit.
Good to know!
