### ISSUE TITLE
semantic 2.0

### ISSUE THREAD

**Issue by aronsuarez** [Semantic-Org/Semantic-UI-Meteor#22]
Hi,

when is comming semantic 2.0?
when you update the meteor package?

i need this very urgent for a project.

Semantic is perfect and very very cool

regards aron

**Comment by nooitaf** [comment]
I would assume on June 30th, with the official release, as the meteor package gets auto-generated. 

https://github.com/Semantic-Org/Semantic-UI/issues/2216#issuecomment-114606850

**Comment by nooitaf** [comment]
I thought it's auto-generating but it seems it isn't, so i re-opened because i don't know. but it will definitely be after the official release ;)

**Comment by aronsuarez** [comment]
Ok, and the official release is on the 30 June?

**Comment by aronsuarez** [comment]
sorry wrong button

**Comment by flemay** [comment]
@nooitaf You are right, this package is not generated automatically. Before publishing a new version of the package I want to make sure that it working fine overall. After 2.0, I will probably integrate my code generator to Semantic UI so it gets generated on version changes.

**Comment by seddonm1** [comment]
@nooitaf 
It would be nice to have a semantic-ui-BETA package available via atmosphere if it fits within their rules.

**Comment by nooitaf** [comment]
@seddonm1 i would rather not clutter atmosphere with beta packages. Specially when its just 1-2 days left till the final release.

**Comment by jlukic** [comment]
@flemay Pinging that 2.0 will be out in 3-4 hours. If you have a chance to update data package later tonight or tomorrow.

**Comment by flemay** [comment]
@jlukic semantic:ui has been updated :) btw, good work with this version! :+1:

**Comment by steve-ross** [comment]
how do you grab the 2.0 version? I'm still getting 1.12.1_1

**Comment by v3rron** [comment]
it's not updating with `meteor update` command.
what worked for me is uninstall > install the package.

**Comment by caprica** [comment]
@v3rron Thanks for posting that, the same thing worked for me.

**Comment by steve-ross** [comment]
agreed thank you... same thing was happening for me

**Comment by jlukic** [comment]
@splendido Have you had a chance to test out 2.0 packages?

**Comment by jlukic** [comment]
@flemay Any chance we can get this updated to `2.0.4`, can this be automated somehow?

**Comment by flemay** [comment]
@jlukic! Updated! Yes it could be automated. the automated process would look like the following:
1. clone 2 packages
2. run my gulp file to update the packages
3. publish packages on meteor and commit the changes to github

I haven't done the step 1 but I have scripts for 2 and 3.

**Comment by jlukic** [comment]
I hear ya, we're doing something similar to create the component distributions, same 3 steps
https://github.com/Semantic-Org/Semantic-UI/tree/master/tasks/admin/distributions

**Comment by jlukic** [comment]
@flemay Wanted to ping `2.1` was just released

**Comment by flemay** [comment]
@jlukic Updated! :)

**Comment by splendido** [comment]
@jlukic: it seems [autopublish.meteor.com](https://autopublish.meteor.com/) received no triggers this time...
Is this something intentional?

**Comment by splendido** [comment]
...single component repositories seem to have been taken back to `v2.0.7`?
see [this commit](https://github.com/Semantic-Org/UI-Message/commit/6e6b780c4e50619fa01795237546b781f07d2412) among the latest ones...

**Comment by jlukic** [comment]
There was a bug with how it was pulling versions. Was looking in `semantic.json` before `package.json`  . Pushing new version now with fix.

**Comment by jlukic** [comment]
@splendido Looks like it all published ok!

**Comment by splendido** [comment]
Great!

**Comment by jlukic** [comment]
@flemay We've had a few patches since `2.1`, any chance we can update?

**Comment by flemay** [comment]
@jlukic Done! :)

**Comment by jlukic** [comment]
@flemay ping on new version `2.1.5`

**Comment by flemay** [comment]
@jlukic Done! :)

**Comment by jlukic** [comment]
:+1:

**Comment by jlukic** [comment]
Pushed `2.1.6` with a bugfix

**Comment by flemay** [comment]
Published! :)
