### ISSUE TITLE
Cards not aligning properly in IE or Safari on iOS

### ISSUE THREAD

**Issue by cyllu2** [Semantic-Org/Semantic-UI-Meteor#26]
This simple HTML,

    <div class="ui padded row">
        <div class="centered column">
            <div class="ui three stackable cards">
                <div class="blue card">fdsfsdf</div>
                <div class="blue card">fdsfsdf</div>
               	<div class="blue card">fdsfsdf</div>
            </div>
        </div>
    </div>

should center the cards and then stack them. However, on IE(10) and Safari on iOS and possibly other browsers as well, they are left-aligned all the time, even when stacked.

**Comment by jlukic** [comment]
hi, please file bugs related to layout in the [main issues repository](https://github.com/Semantic-Org/Semantic-UI/issues). 

I've gone ahead and reposted the issue there.

**Comment by cyllu2** [comment]
Uhhhh but this bug is specific to this package, not Semantic UI as a whole.

**Comment by nooitaf** [comment]
@jlukic "I'll be taking the weekend off of coding..." .. well,.. take it off! .. take it off now! xD
