### ISSUE TITLE
Definition 'container' seems to be missing

### ISSUE THREAD

**Issue by janprill** [Semantic-Org/Semantic-UI-Meteor#29]
After adding semantic:ui to a project and generating the custom.config.json there is no definition for 'container' in there. Adding it manually results in: Semantic UI Generator: definition/theme "container"" does not exist. Please update your custom.semantic.json file. How is one supposed to add the container styles?

Best, Jan

**Comment by dalgard** [comment]
You most likely don't have version 2.0.x of Semantic UI, which introduced the `container` element. Try doing a `meteor update` in your project.
