### ISSUE TITLE
Can't turn anything to false

### ISSUE THREAD

**Issue by cyllu2** [Semantic-Org/Semantic-UI-Meteor#30]
Last version was buggy, but at least you could work around the bugs. This time, you can't turn anything to false in custom.semantic.json or else it throws a complier error. Zzzzzzz

**Comment by flemay** [comment]
I will have a look into it.

"Last version was buggy, but at least you could work around the bugs": Was it really bugs or not explained well how it works?

Cheers

**Comment by flemay** [comment]
I set many things to false without any issue. More details would be much appreciated.

**Comment by giantelk** [comment]
@cyllu2 Is your error the same as issue `BUG: can not find site.variables #34` ?
https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/34
