### ISSUE TITLE
jQuery not defined - custom.semantic.json setup question

### ISSUE THREAD

**Issue by chhudson** [Semantic-Org/Semantic-UI-Meteor#32]
I am trying to setup a basic meteor app 'simple-todos' and i keep running into the 'jQuery not defined' issue. 

To resolve this, I just started to delete things and the css eventually worked. But, I really want the whole theme customization thing :). 

NOTE: I am a new to this...

`ReferenceError: jQuery is not defined
    at app/definitions/behaviors/api.js:1081:5
    at app/definitions/behaviors/api.js:1083:3
    at /home/chudson/Documents/simple-todos/.meteor/local/build/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/home/chudson/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /home/chudson/Documents/simple-todos/.meteor/local/build/programs/server/boot.js:117:5
Exited with code: 8
Your application is crashing. Waiting for file change.`

I went into `api.js` and found the jQuery reference but do not really know where to go from here.

Thanks for any help!

**Comment by chhudson** [comment]
its working now. do not know why but i just changed 'Client/Lib' to client/lib and now it seems to be working just fine....

**Comment by nooitaf** [comment]
Its working now because meteor uses the files in `client/` as files that get loaded on the client. Unix based systems actually care about lower and uppercase characters in foldernames. So if you use `Client/` its just a foldername so the files will get loaded on the server and the client. And as there is no jQuery on the server it throws an error.

Example file structure from http://docs.meteor.com/#/full/structuringyourapp 

``` bash
lib/                      # common code like collections and utilities
lib/methods.js            # Meteor.methods definitions
lib/constants.js          # constants used in the rest of the code

client/compatibility      # legacy libraries that expect to be global
client/lib/               # code for the client to be loaded first
client/lib/helpers.js     # useful helpers for your client code
client/body.html          # content that goes in the <body> of your HTML
client/head.html          # content for <head> of your HTML: <meta> tags, etc
client/style.css          # some CSS code
client/<feature>.html     # HTML templates related to a certain feature
client/<feature>.js       # JavaScript code related to a certain feature

server/lib/permissions.js # sensitive permissions code used by your server
server/publications.js    # Meteor.publish definitions

public/favicon.ico        # app icon

settings.json             # configuration data to be passed to meteor --settings
mobile-config.js          # define icons and metadata for Android/iOS
```
