### ISSUE TITLE
Dropdown don't open

### ISSUE THREAD

**Issue by perak** [Semantic-Org/Semantic-UI-Meteor#33]
Hi,

I just created "hello world" meteor application, and copy&pasted example menu from http://semantic-ui.com/collections/menu.html

```
<div class="ui large menu">
  <a class="active item">
    Home
  </a>
  <a class="item">
    Messages
  </a>
  <div class="right menu">
    <div class="ui dropdown item">
      Language <i class="dropdown icon"></i>
      <div class="menu">
        <a class="item">English</a>
        <a class="item">Russian</a>
        <a class="item">Spanish</a>
      </div>
    </div>
    <div class="item">
        <div class="ui primary button">Sign Up</div>
    </div>
  </div>
</div>
```

It's correctly styled, but dropdown doesn't open (Linux/Chrome).

Do I need to call any jQuery initialization code on Template.rendered ?

Thanks!
Petar

![dropdown_dont_open](https://cloud.githubusercontent.com/assets/5630814/8638253/b5a8b964-28b5-11e5-8c6e-196325b53b01.png)

**Comment by perak** [comment]
It behaves the same in FireFox too - I cannot open dropdown.

**Comment by dalgard** [comment]
Yes, exactly – call `.dropdown()` on the element inside the `rendered` hook.

**Comment by iahvector** [comment]
This fixed it for me:

``` javascript
Template.layout.created = function() {
  $('body').delegate('.dropdown', 'click', function(event) {
    $('.dropdown').dropdown();
  });
};
```

`layout` is my main template. There probably is  better solution than calling it every time it's clicked.

**Comment by sungwoncho** [comment]
I had to do this:

``` javascript
Template.myTemplate.onRendered(function () {
  $('.ui.dropdown').dropdown();
});
```

**Comment by splendido** [comment]
The solution used by @sungwoncho is the correct one! :+1: 

Doing the same on parent templates won't guarantee the same results since child templates might still not be ready when the `onRendered` hook of the parent is triggered...

**Comment by splendido** [comment]
This should be something to add to the [Readme.md](https://github.com/Semantic-Org/Semantic-UI-Meteor/blob/master/README.md) file to get people started the right way...

CC: @flemay

**Comment by splendido** [comment]
See also #16 and [this other comment](https://github.com/Semantic-Org/Semantic-UI/issues/1618#issuecomment-72310597) I posted last January...

**Comment by perak** [comment]
Thank you folks! :)

Closing this issue.
