### ISSUE TITLE
BUG: can not find site.variables

### ISSUE THREAD

**Issue by Chun-Yang** [Semantic-Org/Semantic-UI-Meteor#34]
Thank you for your awesome package.

When I edit custom.semantic.json,

```
themes: {
  // ...
  "default": false,
  "classic": true,
  // ...
}
```

I get error:

```
While building the application:
   client/semantic-ui/theme.import.less:17:1: Less compiler error:
   'themes/default/globals/site.variables' wasn't found. Tried -
   client/semantic-ui/themes/default/globals/site.variables,
   /Users/trent/Work/tax/client/semantic-ui/themes/default/globals/site.variables,
   /Users/trent/Work/tax/themes/default/globals/site.variables,
   themes/default/globals/site.variables
```

But when I change default to true, everything works. Does it mean I ALWAYS need to turn default to true?

**Comment by giantelk** [comment]
I get the exact same error. Steps:
1. In `custom.semantic.json` set `"default":` to `false`.
2. Set `"amazon:"` to `true`.
3. Get this error in Meteor server console:

```
=> Errors prevented startup:                  

   While building the application:
   client/lib/theme.import.less:17:1: Less compiler error: 'themes/default/globals/site.variables' wasn't found. Tried -
   client/lib/themes/default/globals/site.variables,/Users/carlf/Documents/dev/meteor/test/semantic-ui/client/lib/themes/default/globals/site.variables,/Users/carlf/Documents/dev/meteor/test/semantic-ui/themes/default/globals/site.variables,themes/default/globals/site.variables
```

Possibly same as issue `Can't turn anything to false #30`
https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/30

**Comment by Chun-Yang** [comment]
it seems you have to leave default as true

**Comment by nooitaf** [comment]
When you want to use a theme, have a look at the theme's folder first. Themes don't override everything.

The contents of the github theme for example:

``` bash
/themes/github/
├── collections
│   ├── form.overrides
│   ├── form.variables
│   ├── menu.overrides
│   ├── menu.variables
│   ├── message.overrides
│   └── message.variables
└── elements
    ├── button.overrides
    ├── button.variables
    ├── segment.overrides
    ├── segment.variables
    ├── step.overrides
    └── step.variables
```

So you can only use `form, menu, message, button, segment, step` of this theme, there for setting it to `github`. 
Setting `site` to `github` will fail because the theme does not include `globals/site..`.

Thats why the `default` theme needs to be `true`, so you can use it for the things that are not included in a theme.

**Comment by eshell** [comment]
i set everything to false except the defaults and i get this error

**Comment by micktaiwan** [comment]
I didn't modify the example given here https://atmospherejs.com/semantic/ui and I have the same error.

**Comment by giantelk** [comment]
@micktaiwan the default theme needs to be true at ALL times:

themes: {
  // ...
  "default": true,
  "classic": true,
  // ...
}

**Comment by micktaiwan** [comment]
I repeat: I didn't modify the example given here https://atmospherejs.com/semantic/ui

**Comment by nooitaf** [comment]
@micktaiwan can you ge more specific? I just tried it with the auto-generated settings file and that works fine, as aspected. All definitions are true, and the default theme is true too.

``` json
/* custom.semantic.json */
{
  "definitions": {
    "accordion": true,
    "ad": true,
    "api": true,
    "breadcrumb": true,
    "button": true,
    "card": true,
    "checkbox": true,
    "colorize": true,
    "comment": true,
    "container": true,
    "dimmer": true,
    "divider": true,
    "dropdown": true,
    "embed": true,
    "feed": true,
    "flag": true,
    "form": true,
    "grid": true,
    "header": true,
    "icon": true,
    "image": true,
    "input": true,
    "item": true,
    "label": true,
    "list": true,
    "loader": true,
    "menu": true,
    "message": true,
    "modal": true,
    "nag": true,
    "popup": true,
    "progress": true,
    "rail": true,
    "rating": true,
    "reset": true,
    "reveal": true,
    "search": true,
    "segment": true,
    "shape": true,
    "sidebar": true,
    "site": true,
    "state": true,
    "statistic": true,
    "step": true,
    "sticky": true,
    "tab": true,
    "table": true,
    "transition": true,
    "visibility": true,
    "visit": true
  },
  "themes": {
    "amazon": false,
    "basic": false,
    "bookish": false,
    "bootstrap3": false,
    "chubby": false,
    "classic": false,
    "colored": false,
    "default": true,
    "duo": false,
    "fixed": false,
    "flat": false,
    "github": false,
    "gmail": false,
    "instagram": false,
    "material": false,
    "pulsar": false,
    "raised": false,
    "resetcss": false,
    "round": false,
    "rtl": false,
    "striped": false,
    "timeline": false,
    "twitter": false
  }
}
```

**Comment by giantelk** [comment]
@micktaiwan Is it possible you did not remove the file `.custom.semantic.json`

`Note: if you are happy with the default values you will need to remove .custom.semantic.json to generate Semantic UI. (see Generating Trigger)` 
https://atmospherejs.com/semantic/ui

This step caught me too, I missed it. Maybe I initially missed it because it's a grey note, what about making this a numbered step, so people don't miss it? Ideally you should not have to remove files to get the default behaviour, I think the architecture needs changing to make ease of use better. 

Also, if the default theme needs to be true at ALL times, there should not be any option to set it to false. IMHO it's not good for usability/ease of use to show/provide options that aren't really options...(key being "options that aren't options"). At the very least add a comment to the JSON file like:

```
"default": true, // The default option MUST ALWAYS be set to true. Setting default to false will cause zero themes to load.
```

Since comments aren't supported in JSON, could also hack the comment:

```
"default": true, 
"comment_default": "The default option MUST ALWAYS be set to true. Setting default to false will cause zero themes to load."
```

More info on comments in JSON files and various workarounds:
http://stackoverflow.com/questions/244777/can-i-comment-a-json-file

**Comment by micktaiwan** [comment]
I did remove it.
Well, I don't why, but I can't make it work.

**Comment by jlukic** [comment]
This is probably related to this issue
https://github.com/Semantic-Org/Semantic-UI/issues/3009

Fix incoming

**Comment by jlukic** [comment]
Just pushed new version `2.1.4`, see release notes for explanation
https://github.com/Semantic-Org/Semantic-UI/releases/tag/2.1.4

@flemay when you get a chance can you update meteor package :)

**Comment by flemay** [comment]
@jlukic I've updated! Also, I have everything now in place to do something like `./generate-and-publish.sh 2.1.4` :) I will soon move my repo to semantic one. Cheers!

**Comment by pixelpunch** [comment]
Hi,
I have been able to install PAINLESSLY the 'material' theme for meteor, after getting all of the errors mentioned above (and some more). I am a newbie, so am giving step-by-step instructions :)

Here they are -
1.     Create Meteor App
2.      Add Semantic and Autoprfixer 
        $ meteor add semantic:ui flemay:less-autoprefixer
3.     Create directory/folder ‘client’ within the app root folder
4.     Create an empty file within the 'client' folder – custom.semantic.json
5.     Run meteor
       $ meteor
6.     Edit custom.semantic.json
        a.     Themes
                    i.     Default: true
                   ii.     Material : true
7.     Edit theme.config.import.less (inside 'client' )
                   a.     @site       : 'material';
                   b.     @reset     : 'material';
                   c.      @menu   : ‘material’;
                   d.     Then you can keep on changing other options to 'material' whenever you need them.
8.  In client/themes you will find 2 folders - 'default' and 'material' and I expect if I want some other theme it will appaear here.

Hopefully this is helpful.

**Comment by kamalsprasad** [comment]
@pixelpunch Thanks! I'm in the same boat as you (n00b :) ) and really appreciated your instructions as using semantic-ui with meteor finally makes sense. :)
