### ISSUE TITLE
Excluding generated files from source control

### ISSUE THREAD

**Issue by dalgard** [Semantic-Org/Semantic-UI-Meteor#36]
It seems logical to add the automatically generated folders and files to a `/client/lib/semantic-ui/.gitignore` file.

Like this:

```
/definitions/
/themes/
/.custom.semantic.json
/semantic.less
/theme.import.less
```

Am I right?

**Comment by nooitaf** [comment]
Right, the only difference will be that your app might refresh after first start, if it needs regenerating.

**Comment by dalgard** [comment]
Good point – thanks!
