### ISSUE TITLE
Do I need to explicitly down semantic-ui data and less-autoprefixer?

### ISSUE THREAD

**Issue by williamkhshea** [Semantic-Org/Semantic-UI-Meteor#4]
I follows the instruction (download semantic:ui and create a file custom.semantic.json) but still cannot get it working.

I can find the .custom.semantic.json file and didn't see the definitions. thems, sites, etc. folders.

Is there any steps I missed?

**Comment by flemay** [comment]
There is an issue opened for this [here](https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/2). My initial thought was to let the user decide what they want to use from Semantic UI and then generate the files. Feel free to add any comments/suggestions there :)

Basically you need to delete `.custom.semantic.json` and either restart meteor or make a modification in `custom.semantic.json`.

**Comment by v3rron** [comment]
Had the same issue.
I just spent around 3 hours figuring out what's wrong with this package.
Almost ditched the idea of using it. Please make it more automatic or at least explain those issues in the docs.
I'm sure there's plenty of others facing this problem as well. This is a great framework, just needs to be a little more user friendly.
