### ISSUE TITLE
Can't load google font

### ISSUE THREAD

**Issue by zhubofei** [Semantic-Org/Semantic-UI-Meteor#42]
I put

``` Less
@headerFont        : 'Source Sans Pro', sans-serif;
@pageFont          : 'Source Sans Pro', sans-serif;
@fontSmoothing     : antialiased;
@importGoogleFonts : true;
@googleFontFamily  : 'Source+Sans+Pro:400,700,400italic,700italic';
```

in site/globals/site.variables.import.less
But the browser doesn't load the google font files.

**Comment by dmalik** [comment]
What you want is: @googleFontRequest

so:

@googleFontRequest : 'Source+Sans+Pro:400,700,400italic,700italic'';

You can add more than one google font with a pipe |

ex:
@googleFontRequest : 'Source+Sans+Pro:400,700,400italic,700italic|Open+Sans:300italic,400'';

This is loaded in from the 'theme.import.less' file.

**Comment by laurentpayot** [comment]
Because in `/themes/default/globals/site.variables.import.less` we have

``` less
@googleFontRequest : '@{googleFontName}:@{googleFontSizes}&subset=@{googleSubset}';
```

In `/site/globals/site.variables.import.less` I use the following "hard coded" string to add the Bangers font for instance:

``` less
@googleFontRequest: 'Lato:400,700,400italic,700italic|Bangers:400&subset=latin';
```

**Comment by Maxhodges** [comment]
same here. seems Roboto not loaded. using Meteor install.
_site/globals/site.variables.import.less_

```
@fontName          : 'Roboto';
@fontSmoothing     : antialiased;

@headerFont        : @fontName, 'sans-serif';
@pageFont          : @fontName, 'sans-serif';

@googleFontName    : @fontName;
@importGoogleFonts : true;
@googleFontSizes   : '400,700';
@googleSubset      : 'latin';

@googleProtocol    : 'https://';
@googleFontRequest : '@{googleFontName}:@{googleFontSizes}&subset=@{googleSubset}';
```

**Comment by bjornlll** [comment]
Maybe this is a very ignorant question, please excuse me if it is: I can't seem to get Semantic UI to detect any changes to my `site/globals/site.variables.import.less` at all. I've got pretty much the same configuration as @Maxhodges above, but it still fetches and uses the default Lato font when I inspect elements in the Chrome Dev Console.

What am I doing wrong?

**Comment by Maxhodges** [comment]
I actually got it working at some point but can't remember the last thingI had done.

which `site` is that? your default theme or a custom theme override? if custom do you also have it set in 
`client/lib/theme.config.import.less`? e.g.

```LESS
/* To override a theme for an individual element
   specify theme name below
*/

/* Global */
@site: 'blackship';
@reset: 'default';

/* Elements */
@button: 'blackship';
@container: 'default';
...
```

so I have
`client/lib/themes/blackship/globals/site.variables.import.less`
```LESS
@fontName: 'Lato';
@fontSmoothing: antialiased;

@headerFont: @fontName, 'sans-serif';
@pageFont: @fontName, 'sans-serif';

@googleFontName: @fontName;
@importGoogleFonts: true;
@googleFontSizes: '400';
@googleSubset: 'latin';

@googleProtocol: 'https://';
@googleFontRequest: '@{googleFontName}:@{googleFontSizes}&subset=@{googleSubset}';
```
and also `client/lib/theme.import.less`

```less
.loadFonts() when (@importGoogleFonts) {
	@import url('@{googleProtocol}fonts.googleapis.com/css?family=@{googleFontRequest}');

```

**Comment by bjornlll** [comment]
Ok! Thanks. That seems like it should resolve the issue. Really, thanks for taking the time to reply. For now, I have manually overridden the definition files, bad. I'll try out your suggestion.

Unrelated/Off topic/Yet somehow related: I know it's built to be extensible and non-intrusive, but I feel a workflow oriented tutorial would be in place for some of these more common action "How to achieve X". Simplest example would be "How to replace Lato with a Google Font of your choice".

**Comment by Maxhodges** [comment]
yeah I agree. I found SUI really hard to get started with because it's rather sophisticated and complicated and I had less experience with npm and gulp when I started. Would love to have better docs. 
we do have peer to peer forums too at least for now for usage questions

http://forums.semantic-ui.com/
