### ISSUE TITLE
ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by leijing7** [Semantic-Org/Semantic-UI-Meteor#43]
I created a meteor app from scratch, just changed github to true, and the default is still true as well. then 

```
/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150803-08:40:50.074(0)? (STDERR)                             throw(ex);
W20150803-08:40:50.074(0)? (STDERR)                                   ^
W20150803-08:40:50.074(0)? (STDERR) ReferenceError: jQuery is not defined
W20150803-08:40:50.074(0)? (STDERR)     at app/ui/definitions/behaviors/api.js:1122:5
W20150803-08:40:50.074(0)? (STDERR)     at app/ui/definitions/behaviors/api.js:1124:3
W20150803-08:40:50.074(0)? (STDERR)     at /home/sui/test2/.meteor/local/build/programs/server/boot.js:222:10
 W20150803-08:40:50.074(0)? (STDERR)     at Array.forEach (native)
 W20150803-08:40:50.075(0)? (STDERR)     at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
 W20150803-08:40:50.075(0)? (STDERR)     at /home/sui/test2/.meteor/local/build/programs/server/boot.js:117:5
```

**Comment by splendido** [comment]
Seems to be the same as #14

**Comment by leijing7** [comment]
splendido, you are right. It is the same as #14. Please close this one.
For other person has the same problem. You have to put the custom.semantic.json file to /client/lib, because meteor only treats code in the dir called client as frontend code, otherwise meteor thinks they are server side code, then can not find jQuery of course.
Maybe the doc should mention this explicitly so people might meet less problem especially novices.

**Comment by splendido** [comment]
Ok, thanks for the pointer, I'll link to your comment from #14

**Comment by bevinhex** [comment]
Same here
using Linux

**Comment by john-osullivan** [comment]
Has anyone tried doing Server-Side Rendering using this package?  My stack is Meteor + React + Semantic-UI, but I'm having some trouble getting Semantic-UI to work properly when using `react-router-ssr` to render React components on the server.  All of the actual files I require (e.g. files in `modules` and `behaviors`) only get referenced after the page is on the client's machine.  Do y'all know of anyone else combining these technologies?
