### ISSUE TITLE
How to initial all components on formbuilder or else...

### ISSUE THREAD

**Issue by carrot93** [Semantic-Org/Semantic-UI-Meteor#46]
I must initial components of semantic-ui like,radio,dropdown,checkbox. But for the formbuilder sense, we can't know the components to be view as well. 

In meteor, like autoform generator, we need initial the semantic-ui parts like

```
Template.test.rendered = () ->
   $('ui.checkbox').checkbox();
   $('ui.radio').checkbox;
   $('ui.menu').dropdown(); 
```

But there's no effect sometimes. 

Any idea to initial all components of semantic-ui, for more useful sense like Page Genterator.

**Comment by mcrayne** [comment]
Not sure if it makes a difference but `Template.test.rendered = () ->` should be 

`Template.test.onRendered(()=> { ... }` 

Some of the components will render without JS but they are ugly and don't work as you expect - more like plain HTML elements.
