### ISSUE TITLE
I can't get the stackable grid to work on mobile

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI-Meteor#47]
I am using Meteor and Semantic-ui 2 and can't get the stackable grid to work on mobile (iPhone 6). When I resize my computer screen everything works fine but not on the mobile. On the mobile I have 3 columns and space on the sides (just as a large screen). It should be stacked in one column and use 100% of the screen. As I can understand mobile is defined as below 768px and iPhone6 is 750px. Do anyone have any suggestions or answers to solve this?

```
<div class="ui three column stackable grid container">
        <div class="four wide column"></div>
        <div class="nine wide column"></div>
        <div class="three wide column"></div>
</div>
```

**Comment by ghost** [comment]
Is there anyone who has managed to use 100% screen width when using the Semantics-ui (2) class "container" on a mobile?

**Comment by rufusthecat** [comment]
Hey 
Have you tried adding this in your metadata. I had the same issue

`<meta name=viewport content="width=device-width, initial-scale=1">`

**Comment by ghost** [comment]
Hi
Thanks a lot rufusthecat. I thought meteor handle it by default. I used semnatic-ui.css earlier and can't remember I specified the meta tag. Anyway, I added the meta tag and everythings works fine, a big thanks.
