### ISSUE TITLE
site: false causing issues

### ISSUE THREAD

**Issue by purplecones** [Semantic-Org/Semantic-UI-Meteor#48]
When i change the site property to false, I am getting the following error:

```
   While building the application:
   client/lib/semantic-ui/theme.import.less:17:1: Less compiler error:
   'themes/default/globals/site.variables' wasn't found. Tried -
   client/lib/semantic-ui/themes/default/globals/site.variables,/Users/xxxx/xxxx/xxxx/client/lib/semantic-ui/themes/default/globals/site.variables,/Users/xxxx/xxxx/xxxx/themes/default/globals/site.variables,themes/default/globals/site.variables
```

setting it to true again does not throw the error.

**Comment by derwaldgeist** [comment]
Bump. As I only wanted a part of Semantic UI, I deleted the other items and ran into the same problem. The same happens if you set the 'default' theme to false. Obviously, both 'site' and default theme are required.
