### ISSUE TITLE
Add a build option. 

### ISSUE THREAD

**Issue by drew-y** [Semantic-Org/Semantic-UI-Meteor#5]
It would be nice if there was an option to build so that I could then integrate the /dist into the app. This would eliminate the need to recompile less after I am done tweaking the components and themes. Or is this possible already and I just don't know it?

**Comment by flemay** [comment]
You could probably use the semantic src folder, compile it and then integrate it into your project. :)

**Comment by drew-y** [comment]
I'll try that out, Thanks!
