### ISSUE TITLE
Modal not destroyed after route change

### ISSUE THREAD

**Issue by sangyoo91** [Semantic-Org/Semantic-UI-Meteor#50]
Modal will not destroy itself when route/template is changed.

**Comment by oliverlloyd** [comment]
Try using:

```javascript
$('.my.modal').modal({
  detachable: false,
});
```

**Comment by craigdrayton** [comment]
I was able to solve this with the help of this hackpad:
https://meteor.hackpad.com/A-pattern-for-incorporating-modals-wo8Uhynt02r
