### ISSUE TITLE
Feature request: add .gitignore file

### ISSUE THREAD

**Issue by rijk** [Semantic-Org/Semantic-UI-Meteor#53]
After installing the package, a number of directories and files are created in the `lib/semantic-ui` directory, some of which are generated when running `meteor` and thus not to be edited. To keep my repo clean, I want to exclude these files from the commit. To do this, I've added the following to `lib/semantic-ui/.gitignore`:

```
definitions
themes
.custom.semantic.json
semantic.less
theme.import.less
```

It might be useful to add this file by default when generating the other files (in the same way as `theme.config.import.less` is handled; "only if the file does not exist"), to make the package easier to use. What do you think?

**Comment by flemay** [comment]
How would you deploy on production without those files?

**Comment by rijk** [comment]
Hm, good point maybe.. I deploy with the modulus cli so it's no problem (it will just upload all the files from your computer). How it works with other methods I'm not sure.

**Comment by flemay** [comment]
I see! I still believe I would keep those files in my repo because I don't want to regenerate them. Moreover you could remove the plugin and it will still work with those files! :)

**Comment by rijk** [comment]
Ah ok, thanks for explaining! The way I saw it was more like a package; your repo only contains a link to the package (in `.meteor/packages`) and the code to configure the package for your app (like `at_config.js`). The package code itself is downloaded when running Meteor. But maybe that way of thinking doesn't apply here?

**Comment by merlinstardust** [comment]
I'm new to Semantic and also have this issue. I want to keep my repo clean like @rijk. According to the [README](https://github.com/Semantic-Org/Semantic-UI-Meteor/#generated-structure), the files and folders listed above are generated every time Meteor is run. Based on that, you should be able to ignore them, since your server will just generate them again. Is there some flaw in this logic?

**Comment by ubald** [comment]
They will be generated when run with `meteor run` but not when doing `meteor build`. I too want to keep my repo clean but It seems impossible for the moment. I opened an issue here for the build not generating the required files. https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/83
