### ISSUE TITLE
Jquery is not defined

### ISSUE THREAD

**Issue by milincheta** [Semantic-Org/Semantic-UI-Meteor#59]
Hi, I am trying to use Semantic UI for an existing app.
I have installed Semantic as detailed here: https://github.com/Semantic-Org/Semantic-UI-Meteor/blob/master/README.md
As it says I have created:
Client\lib\custom.semantic.json

Everything should be ok, but unfortunatelly it not. When I run the project I get the following error:

W20150904-01:15:55.226(-3)? (STDERR) ReferenceError: jQuery is not defined
W20150904-01:15:55.226(-3)? (STDERR)     at app\Client\lib\semantic-ui\definitio
ns\behaviors\api.js:1140:5
W20150904-01:15:55.226(-3)? (STDERR)     at app\Client\lib\semantic-ui\definitio
ns\behaviors\api.js:1142:3

Thanks.

**Comment by nooitaf** [comment]
Use lower case `client` like it says in https://github.com/Semantic-Org/Semantic-UI-Meteor/blob/master/README.md#usage

It complains because `Client` gets interpreted as "just a folder" and it tries to load jquery on the client and the server, and there is no jquery on the server.

**Comment by milincheta** [comment]
Ok thanks! will try it later.
Could you edit said file and state that it is case sensitive?
That will make newbies -like me- life easier.
Thanks!

**Comment by nooitaf** [comment]
As its meteor basics, i guess you would have faced this problem with any client or server package on first use of folders. You just used this one first ^^. http://docs.meteor.com/#/full/structuringyourapp
But maybe its a good idea to emphasize that its a client package though.

btw, after  using `meteor create appname` i always throw away the auto-created files and create a base structure like this:

``` text
.
├── lib/
│   └── common.js
├── client/
│   ├── client.css
│   ├── client.html
│   └── client.js
└── server/
    └── server.js
```

As the project gets more complex its reasonable to create more files, etc..

You can also split it up like this:

``` text
.
├── foo/
│   ├── client/
│   │   ├── client.css
│   │   ├── client.html
│   │   └── client.js
│   ├── lib/
│   │   └── common.js
│   └── server/
│       └── server.js
└── bar/
    ├── client/
    │   ├── client.css
    │   ├── client.html
    │   └── client.js
    ├── lib/
    │   └── common.js
    └── server/
        └── server.js
```

cheers!

**Comment by milincheta** [comment]
Thanks for your feedback!
In fact I have tried other packages that didn't work...I see now why!
Have a nice weekend.

**Comment by milincheta** [comment]
I did try what you suggest. The error is gone.
But Semantic (I guess) has broken iron:router.
Love it...

**Comment by nooitaf** [comment]
Highly unlikely...
