### ISSUE TITLE
Release 1.12.1 is out...

### ISSUE THREAD

**Issue by splendido** [Semantic-Org/Semantic-UI-Meteor#6]
what about the integration with the SUI build workflow?

**Comment by flemay** [comment]
I don't have time to look into the workflow but I am happy to share my gulp file :)

**Comment by flemay** [comment]
I have updated to version 1.12.1 :)

I have created a script to commit on github and publish on atmosphere so in the process to test the workflow.

**Comment by splendido** [comment]
Could you share the script?
perhaps @jlukic could manage to integrate it into the SUI build workflow...

Once this will be done, new versions will be autopublished :)

**Comment by flemay** [comment]
My main concern now is the lack of any automated test..
