### ISSUE TITLE
autofocus not working for modal

### ISSUE THREAD

**Issue by garyfoo** [Semantic-Org/Semantic-UI-Meteor#60]
Hello, I'm developing a web app using this package and I just realized that autofocus doesn't work for the first input element. Would you kindly look into this issue?

Note: autofocus for modals work fine usng JQuery and the official semantic ui package. Not sure what's the issue here :/

**Comment by nooitaf** [comment]
Maybe not the best solution, but this works...
```javascript
Template.mytemplate.onRendered(function(){
  setTimeout(function(){
    $('.modal')
      .modal({autofocus:true})
      .modal('show')
  },100)
})
```
