### ISSUE TITLE
Can we stop using less-autoprefixer?

### ISSUE THREAD

**Issue by micahalcorn** [Semantic-Org/Semantic-UI-Meteor#62]
[There seems to be an issue with using less-autoprefixer in Meteor 1.2.](https://github.com/flemay/less-autoprefixer/issues/4)

This is all above my pay grade (amateur/hobbyist), but it is my understanding that [Meteor now has a build process for LESS to CSS compilation](https://github.com/meteor/meteor/wiki/Build-Plugins-API#build-plugins-in-isobuild). Can that be used instead of the autoprefixer package? I am currently stuck trying to upgrade.

**Comment by sircharleswatson** [comment]
@micahalcorn I just made a fix for this and will be making a pull-request soon.

**Comment by micahalcorn** [comment]
@sircharleswatson great, thanks so much.

**Comment by sircharleswatson** [comment]
@micahalcorn also, my PR allows both(one or the other) less processors to be used (and they both work properly as far as I can tell)

**Comment by flemay** [comment]
I should probably update the less-autoprefixer to the new build process in meteor 1.2.

@sircharleswatson The reason behind `less-autoprefixer` is to be able to add `autoprefixer` to `Semantic UI` as it uses it. I am not aware if that has changed or not.

@sircharleswatson I am really interested in your fix :)

**Comment by flemay** [comment]
@micahalcorn I've "merged" @sircharleswatson fix but you would still need autoprefixer.

**Comment by flemay** [comment]
@micahalcorn did you have any problem with less-autoprefixer in meteor 1.2?

**Comment by micahalcorn** [comment]
Yes, same as you are aware of at https://github.com/flemay/less-autoprefixer/issues/4.

**Comment by flemay** [comment]
@micahalcorn their issue was the inclusion of both `less` and `flemay:less-autoprefixer`.
