### ISSUE TITLE
Meteor 1.2 plugin issue

### ISSUE THREAD

**Issue by sircharleswatson** [Semantic-Org/Semantic-UI-Meteor#63]
I'm trying to put semantic:ui into a package for my app and I'm running into issues with the app not being able to handle some of the files.

```
Package.onUse(function(api) {
  api.versionsFrom('1.2')
  api.use([
    'ecmascript',
    'flemay:less-autoprefixer@1.1.0',
    'semantic:ui@2.1.4'
  ])

  api.addFiles(clientFiles, 'client')
})
```

The error I get is:

```
error: No plugin known to handle file 'lib/client/semantic-ui/.custom.semantic.json'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
   api.addAssets('lib/client/semantic-ui/.custom.semantic.json', 'client').
   error: No plugin known to handle file 'lib/client/semantic-ui/custom.semantic.json'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
   api.addAssets('lib/client/semantic-ui/custom.semantic.json', 'client').
   error: No plugin known to handle file 'lib/client/semantic-ui/definitions/collections/breadcrumb.import.less'. If you want this file to be a static asset, use addAssets
   instead of addFiles; eg, api.addAssets('lib/client/semantic-ui/definitions/collections/breadcrumb.import.less', 'client').
...
...
// there are a lot more files that get this error
```

I hope you can help me! I'd really like to keep the semantic stuff in a package rather than in the app itself.

**Comment by sircharleswatson** [comment]
Ok, so, I moved the semantic stuff from `client/lib/semantic-ui/` to `client/semantic-ui` and it works just fine. Not sure why it doesn't work if it's in the lib folder.

**Comment by sircharleswatson** [comment]
I fixed this issue and will be making a PR soon!

**Comment by flemay** [comment]
@sircharleswatson I am in the process to upgrade to 1.2 so I now use api.addAssets. However, when I use [file.AddAsset](https://github.com/meteor/meteor/wiki/Build-Plugins-API) to add icons and flags, nothing appears on the web page. :|

**Comment by flemay** [comment]
I've updated packages to 2.1.4_3 with the fix. :)

**Comment by juliomac** [comment]
Hi @flemay , I have the same issue but `Meteor update` breaks with this error and does not update anything. It seems not to be able to continue the update process.

Edit: Just changed addFiles to addAssets on the `packages.json` and it worked fine.

**Comment by flemay** [comment]
@juliomac package 2.1.4_5 should have now addAssets :)

**Comment by fvpDev** [comment]
Can we close this?

**Comment by juliomac** [comment]
Yes for me. THANKS!
