### ISSUE TITLE
2.1.4_2 fonts issue

### ISSUE THREAD

**Issue by v3rron** [Semantic-Org/Semantic-UI-Meteor#66]
Just updated to 2.1.4_2 and having squares instead of all my icons.
Also getting the console error:

```
Failed to decode downloaded font: http://localhost:3000/themes/default/assets/fonts/icons.woff2 
OTS parsing error: invalid version tag
```

If I revert back to 2.1.4, it works fine.

**Comment by flemay** [comment]
@v3rron  Yes, I need to fix it! Need to update my package to the new build system. For now it's best to stick with 2.1.4.

**Comment by reimertz** [comment]
How do you guys set it to 2.1.4? 

when I do meteor 

```
add semantic:ui@2.1.4 
```

I still get 

```
semantic:ui       added, version 2.1.4_2
semantic:ui-data  added, version 2.1.4_2
```

**Comment by v3rron** [comment]
@reimertz you can just edit it manually in .meteor/versions file. But you will also need to delete semantic-ui folder and reinstall it.

**Comment by v3rron** [comment]
@flemay that would be great, looking forward for a new version :)

**Comment by reimertz** [comment]
Thanks @v3rron!

**Comment by reimertz** [comment]
This did the trick

```
meteor add semantic:ui@=2.1.4
meteor add semantic:ui-data@=2.1.4
```

**Comment by flemay** [comment]
I've "removed" the packages (version 2.1.4_1, 2.1.4_2) from atmosphere.

**Comment by bukaicode** [comment]
So glad I found this! I thought I was going crazy. Thanks for the workaround.

**Comment by flemay** [comment]
I've updated to 2.1.4_3 with the fix. :)

**Comment by minfawang** [comment]
Hi @flemay, I just updated my semantic:ui and semantic:ui-data version to `2.1.4_5` but I'm still getting the error :cry:

**Comment by minfawang** [comment]
@flemay Oh never mind. After I removed the old auto-generated `semantic-ui` configuration folder from my project, and re-generate the new one. The icon starts to work!

**Comment by flemay** [comment]
Good. I will close this issue. :)
