### ISSUE TITLE
falling back to default theme

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI-Meteor#7]
First off - kudos for making customizable Semantic package for Meteor, at long last!))
My issue is: i've just spent a couple hours trying to change a theme before realizing that each  element has a different set of applicable themes - well, i'm a SemUI noob)
But wouldnt it be intuitive instead of sending an error in less compiler - fall back to default theme if the component doesn't support selected theme?
Or maybe I should address this issue to the main Semantic development repository?

**Comment by flemay** [comment]
Thank you :)

I personally prefer the error so I know what is going on. What if you don't want/include the default theme?
