### ISSUE TITLE
Installation fail. ENOENT, no such file or directory 'client/lib/semantic-ui'

### ISSUE THREAD

**Issue by xuv** [Semantic-Org/Semantic-UI-Meteor#75]
Just followed the first steps of installation:
1. `meteor add semantic:ui flemay:less-autoprefixer jquery`
2. Created file `custom.semantic.json` in `client/lib/semantic-ui/`

Launched meteor and I get: 

```
=> Errors prevented startup:                  

   While processing files with semantic:ui (for target web.browser):
   client/lib/semantic-ui/custom.semantic.json: Semantic UI Generator: ENOENT, no such file or directory 'client/lib/semantic-ui'

=> Your application has errors. Waiting for file change.
```

Moved the `custom.semantic.json` around, but still same problem. 
Any idea?

**Comment by nooitaf** [comment]
The file has to be completly empty, no spaces no nothing. It will then fill its contents with properties. Edit `custom.semantic.json` and set `basic` to true, save, and it should create everything.

I just did this ..

``` bash
meteor create suitest
cd suitest
# [ apply semantic:ui install here ]
mkdir -p client/lib/semantic-ui/
touch client/lib/semantic-ui/custom.semantic.json
meteor
# meteor starts
# meteor refreshes and updates the file
-- edit `custom.semantic.json` file "basic to true"
-- save the file
# meteor refreshes and should create the rest
```

**Comment by xuv** [comment]
@nooitaf Ok, my bad. Don't know what I did wrong before.
I ran your example (which btw forgets to install semantic:ui ;) ) and it worked.
I went back to my project. Went to every steps again, and now it worked.
I have no idea what went wrong at first. I did use `touch` the first time to create the files. Very weird. But thanks a lot for your help.

**Comment by nooitaf** [comment]
I just had this issue. It happenes for me when i start my app from within a folder of the app, for example the `packages/` folder. 
```bash
cd myapp
cd packages
meteor
# ENOENT
cd ..
meteor
# All Good
```
