### ISSUE TITLE
Select allowAdditions not working

### ISSUE THREAD

**Issue by ryanswapp** [Semantic-Org/Semantic-UI-Meteor#76]
I'm to the point now where I think there may be something wrong with the semantic ui package as I've copied the select code directly from the docs and the allowAdditions option is still not working. Here is my code:

```
<div class="field">
    <label for="languages">Supported Languages</label>
    <select name="languages" class="ui fluid multiple search selection dropdown" id="languages" multiple="">
          <option value="">Languages</option>
                {{#each langs}}
                       <option value="{{name}}">{{name}}</option>
                {{/each}}
     </select>
 </div>
```

I'm instantiating the select with this code:

```
$('.ui.dropdown').dropdown({
            allowAdditions: true
        });
```

Is this a known problem/limitation? Or am I doing something wrong?

**Comment by flemay** [comment]
Your code snippet feels a bit incomplete but I managed to make the following working.

``` html
<template name="allowadditions">
  <div class="field">
      <label for="languages">Supported Languages</label>
      <select name="languages" class="ui fluid multiple search selection dropdown" id="languages" multiple="">
            <option value="">Languages</option>
                  {{#each langs}}
                         <option value="{{name}}">{{name}}</option>
                  {{/each}}
       </select>
   </div>
</template>
```

``` javascript
Template.allowadditions.helpers({
  langs: [{name: 'English'}, {name: 'French'}, {name: 'Spanish'}]
});

Template.allowadditions.rendered = function() {
  $('.ui.dropdown').dropdown({allowAdditions: true});
}
```

**Comment by ryanswapp** [comment]
@flemay The allowAdditions feature is working for you with that code? My code is virtually identical and when I type something in the select field I don't get the "Add ...." message that's supposed to show up. I left out the template js code for brevity.

**Comment by ryanswapp** [comment]
This is driving me crazy... I've been trying to get it to work for hours and it won't work. It works the first time and then never works again. If I change the code it will work the first time and then never work again. No idea what is going on.

**Comment by flemay** [comment]
Have you tried it on a very small project? Like having just one template, jquery, semanticui and less-autoprefixer?

**Comment by ryanswapp** [comment]
Nope. Just trying to get it to work in my production app.

**Comment by flemay** [comment]
So it is working in development environment then?

**Comment by ryanswapp** [comment]
No it's not working at all in my app. I actually went a different route and scrapped using the semantic dropdown.
