### ISSUE TITLE
Error after updating to version 2.1.5 or above

### ISSUE THREAD

**Issue by minfawang** [Semantic-Org/Semantic-UI-Meteor#79]
I have seen issue #75 and I'm getting the same error. The error message is as below:

```
=> Errors prevented startup:

   While processing files with semantic:ui (for target web.browser):
   client/lib/semantic-ui/custom.semantic.json: Semantic UI Generator: ENOENT, no such file or directory
   'client/lib/semantic-ui/definitions'

=> Your application has errors. Waiting for file change.
```

Differently I have been using semantic-ui for a long time. And I tired to remove the `client/lib/semanti-ui` completely and recreate it. The error still didn't go away.

After I downgrade the package version to 2.1.4 with the command `meteor add semantic:ui@=2.1.4`, the problem solved. So I believe there are indeed broken changes incurred from recent updates.

Any ideas?

**Comment by flemay** [comment]
Hi @minfawang !

Thank you for reporting. Would it be possible for you to start a new project to replicate the issue so that you can push on github? :) It would help me a lot.

**Comment by minfawang** [comment]
@flemay Eh.. It's weird. The errors are gone when I just create a new project and repeat the steps. 

I thought there might be conflicts between semantic-ui and other packages that I installed, and then I installed every package that I was using in the original project. The application still runs without a problem.

Sorry that I'm unable to reproduce this issue, and I guess I will stick to version `2.1.4` for now. If others encounter the same problem, hopefully they could provide some more information.

**Comment by sungwoncho** [comment]
I am seeing this on semantic:ui 2.1.6 and Meteor 1.2.1.  My `custom.semantic.json` is completely empty and is located in `client/lib/semantic-ui`. When I create a new repo to reproduce the error, the problem goes away.

**Comment by lfilho** [comment]
Same here. My context: everything was working fine. Then I moved a lot of files around, changed some folder structures, **BUT** I left `client/lib/semantic-ui` untouched and then started receiving this error...

Does it have something like a cache that ti might be looking for the old file's locations or something? Then again, I don't see how the other files should interfere with the package in question...

**Comment by lfilho** [comment]
I removed `.meteor/local/build`, fired `meteor` again and it worked.

**Comment by athyuttamre** [comment]
Can confirm, still facing this issue. Probably going to go down 2.1.4 for now.

**Comment by Kiel-H-Byrne** [comment]
Same thing is happening to me. 
i had a regular "client\lib\semantic-ui" in place with .custom.semantic.json in place..
i started making changes to the dotted json file (.custom.semantic.json) and wasn't noticing the environment update or change... then i realized i didn't have a regular "custom.semantic.json" in place. 

I created a "custom.semantic.json" file and removed the dotted file assuming that it would be recreated as well as folders being updated.. but THIS is when i started receiving the dreaded ENOENT error.. 

removed everything in the folder and tried to start from scratch, but still received error. 
i had to run a git stash and go back to having only the dotted file and associated folder structure... 

when i create a new Meteor project, add semantic-ui, add a blank new custom.semantic.json file to the mix, it gets filled in automatically but no folders get created to support it.. what gives?

**Comment by nooitaf** [comment]
This also happens when your start your app from within a subfolder of your app.
