### ISSUE TITLE
"meteor build" not building semantic-ui

### ISSUE THREAD

**Issue by ubald** [Semantic-Org/Semantic-UI-Meteor#83]
When doing a `meteor build` from a fresh git clone (without the gitignored `definitions`, `themes`, `.custom.semantic.json`, `semantic.less` nor `theme.import.less`), the plugin will not generate the missing files and built semantic-ui.

Only running the application locally with `meteor run` will generate the files, which is not a valid scenario for implementing an automated build system.

Thanks

**Comment by s-devaney** [comment]
So basically deploying this in a production app is not possible. And this issue has been open for 9 months?

**Comment by ubald** [comment]
I had to add the generated files to the project's repo to deploy in production

**Comment by daquintero** [comment]
Has this problem been solved? Having exactly the same issue with gulp build, and gulp run.

**Comment by ubald** [comment]
I couldn't say, I don't use Meteor anymore.
