### ISSUE TITLE
Upgrade atmosphere package to 2.1.8

### ISSUE THREAD

**Issue by talha-asad** [Semantic-Org/Semantic-UI-Meteor#84]
Generally we had been getting updates on this package as soon as a version was released, but this time you missed to update it.

cc @jlukic

**Comment by jlukic** [comment]
@flemay

**Comment by flemay** [comment]
Updated to 2.1.8.

I also open sourced the generator here https://github.com/flemay/meteorize-semantic-ui

**Comment by talha-asad** [comment]
Thanks.
