### ISSUE TITLE
where am I supposed to put the javascript in my meteor app?

### ISSUE THREAD

**Issue by streamnsight** [Semantic-Org/Semantic-UI-Meteor#85]
So far I have simply put the javascript into a <script></script> tag inline in the template, but there must be a better way.

If I use the jQuery style syntax in the `onCreate` or `onRendered`, it doesn't work (function does not exist) 
so where am I supposed to put the Semantic-ui declarations in my Meteor app?

A short example would be nice in the docs.

thanks

**Comment by mcrayne** [comment]
I am not sure what Javascript you are talking about - but I feel your pain. It is, like many things, really simple when you don't think about it too much. Adding the Semantic-UI package makes it available anywhere in your app on the client side. Then, to add javascript to dropdowns, selects (which actually use a menu metaphor to override the ugly "native" dropdowns that smartphones try to have you use), accordions, etc (all of the "modules") you can add them to the onRendered callback in the associated template. It is simply adding jquery selector (either the id or class name) and name of the javascript component like this

`$('.ui.accordion').accordion({options});`

You can then add custom event handlers to whatever callbacks are exposed by the component - by default the `initialize` `refresh` and `destroy` life-cycle event hooks and others like `onChange` or `onBlur` depending on the module - you can read about each in the Usage tab for each component.

If you get stuck using the $form.forms() component - don't let yourself feel stupid. I have spent a crazy amount of time trying to use the built in capabilities for serializing and loading data - it is ugly and I am sure I am doing something wrong. Right now I know I am using a hack but it would be nice to be able to call `.form('set values',  formData)` and have it update all fields - except it does strange things with caching values that really doesn't work well with the "Meteor way" - at least not the way I am doing it.

Good luck,

**Comment by streamnsight** [comment]
i figured it out. i think it didn't have an additional package that was required.

**Comment by AndrewPrifer** [comment]
@streamnsight which package? I'm having the same problem. This:

``` javascript
Template.tpl.onRendered(function () {
  $('.toggle-popup')
    .popup({
      popup: '.popup',
      on: 'click',
    });
});
```

doesn't work ([Log] TypeError: $('.js-toggle-search-settings').popup is not a function. (In '$('.js-toggle-search-settings').popup', '$('.js-toggle-search-settings').popup' is undefined) (meteor.js, line 930)). scoping it to the tamplate (this.$) also doesn't work.

**Comment by AndrewPrifer** [comment]
Problem solved. Meteor 1.3 puzzled me a bit. I accidentally put it in the imports directory and the js files didn't load.

**Comment by fvpDev** [comment]
Closing this

**Comment by partounian** [comment]
@andrewpeterprifer Can you please elaborate on your fix or a give us a link to the repo?
