### ISSUE TITLE
Update to 2.2

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI-Meteor#95]
Hey @flemay just released 2.2 tonight. When you get a chance could you update the package?

**Comment by humbertocruz** [comment]
very nice! :D

**Comment by LarsBuur** [comment]
+1

**Comment by ckiely91** [comment]
+1

**Comment by flemay** [comment]
@jlukic I will do it this week :)

**Comment by Almaju** [comment]
+1
Thanks for your awesome work! :)

**Comment by flemay** [comment]
@jlukic Done. However I cannot see version 2.2.1 in atmosphere :S
@Almaju Thanks! Just wanna say that the package hasn't been tested for meteor 1.3.

**Comment by humbertocruz** [comment]
Working nice on 1.3.4.1 here... just a problem with repeated class name removed by meteor.
