### ISSUE TITLE
flemay:less-autoprefixer is no longer supported

### ISSUE THREAD

**Issue by s-devaney** [Semantic-Org/Semantic-UI-Meteor#96]
[This is causing issues with the latest version of Meteor](https://github.com/meteor/meteor/issues/7206)

[The author of the package has no plans to make it compatible with the latest version](https://github.com/flemay/less-autoprefixer/issues/10)

**Comment by fvpDev** [comment]
See http://semantic-ui.com/introduction/integrations.html for instructions on Meteor integration.
