### ISSUE TITLE
Not Working / METEOR@1.4

### ISSUE THREAD

**Issue by jpsantosbh** [Semantic-Org/Semantic-UI-Meteor#99]
I just create a new app,

meteor remove standard-minifier-css
meteor add semantic:ui juliancwirko:postcss less jquery

And put the blank file
/client/lib/semantic/custom.semantic.json

The build is trigger cause file is not empty any more, but files struture are not created and semantic is not merge at final css

**Comment by v3rron** [comment]
It seems like there's some issues with `juliancwirko:postcss` package. Based on this https://github.com/juliancwirko/meteor-postcss/issues/22 issue it's not going to be maintained anymore. We probably should find an alternative way of using SemanticUI for Meteor. Any thoughts?

**Comment by Orbyt** [comment]
@jpsantosbh Try changing an option in your `custom.semantic.json` and then resaving. This triggered semantic to generate the various directories for me.

**Comment by pefdow** [comment]
@Orbyt thanks that worked

**Comment by fvpDev** [comment]
@jpsantosbh Can I close this?

**Comment by jpsantosbh** [comment]
Yes go ahead
